baseURL = 'https://jianfu.me/'
title = 'Jian Fu - My Sweet Home'
theme = 'hugo-coder'
languageCode = 'en-us'
defaultContentLanguage = "en"
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "Jian Fu"
  info = ["Father", "Surfskater", "Guitar Player"]
  colorscheme = "auto"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "TIL"
  weight = 2
  url = "til/"
